export var GraphicVal = [
  '---',
  'Topsoil',
  'Weathered Rock',
  'Aggregate Base Material',
  'Asphalt',
  'Concrete',
  'Fill',
  'USCS High Plasticity clay',
  'USCS Low Plasticity Clay',
  'USCS Low to High Plasticity Clay',
  'USCS Low Plasticity Gravelly Clay',
  'USCS Low Plasticity Silty Clay',
  'USCS Low Plasticity Sandy Clay',
  'USCS Clayey Gravel',
  'USCS Silty Gravel',
  'USCS Poorly-graded Gravel',
  'USCS Poorly-graded Gravel with Clay',
  'USCS Poorly-graded Gravel with Silt',
  'USCS Poorly-graded Sand with Clay',
  'USCS Well-graded Gravel',
  'USCS Well-graded Gravel with Clay',
  'USCS Well-graded Gravel with Silt',
  'USCS Well-graded Sandy Gravel',
  'USCS Elastic Silt',
  'USCS Silt',
  'USCS Gravelly Silt',
  'USCS Sandy Silt',
  'USCS High Plasticity Organic Silt or Clay',
  'USCS High Plasticity Organic Silt or Clay with Shells',
  'USCS Low Plasticity Organic Silt or Clay',
  'USCS Low Plasticity Organic Silt or Clay with Shells',
  'USCS Peat',
  'USCS Clayey Sand',
  'USCS Silty Clayey Sand',
  'USCS Silty Sand',
  'USCS Poorly-graded Sand',
  'USCS Poorly-graded Gravelly Sand',
  'USCS Poorly-graded Sand with Clay',
  'USCS Poorly-graded Sand with Silt',
  'USCS Well-graded Sandy Gravel',
  'USCS Well-graded Gravelly Sand',
  'USCS Well-graded Sand with Clay',
  'USCS Well-graded Sand with Silt',
  'AASHTO Poorly-graded Gravels, Gravel-Sand Mixtures, Little or No Fines',
  'AASHTO Well-graded Gravels, Gravel-Sand Mixtures, Little or No Fines',
  'AASHTO Silty Sands, Sand-Silt Mixtures',
  'AASHTO Silty Gravels, Gravel-Sand-Silt Mixtures',
  'AASHTO Clayey Sands, Sand-Clay Mixtures',
  'AASHTO Clayey Gravels, Gravel-Sand-Clay Mixtures',
  'AASHTO Poorly-graded Sands, Gravelly Sand, Little or No Fines',
  'AASHTO Silt',
  'AASHTO Elastic Silt',
  'AASHTO Low Plasticity Clay',
  'AASHTO High Plasticity Clay',
  'Soil and Weathered Rocks',
  'Basalt',
  'Bedrock',
  'Boulders and Cobbles',
  'Breccia',
  'Chalk',
  'High Plasticity Clay and Elastic Silt',
  'Clayey Chert',
  'Coal',
  'Coral',
  'Decomposed Rock',
  'Metamorphic Rock',
  'Gypsum, Rocksalt, etc.',
  'Sandstone',
  'Sandstone/Shale',
  'Sandy Clay',
  'Sandy Clay with Cobbles and Boulders',
  'Shale',
  'Siltstone',
  'Glacial Till',
];
export var USCSNameVal = [
  '---',
  'TOPSOIL',
  'WEATHERED ROCK',
  'AGGREGATE BASE',
  'ASPHALT',
  'BEDROCK',
  'CHALK',
  'CHERT',
  'CLAYEY GRAVEL (GC)',
  'CLAYEY SAND (SC)',
  'COAL',
  'CONCRETE',
  'DECOMPOSED ROCK',
  'DOLOMITE',
  'ELASTIC SILT (MH)',
  'FAT CLAY (CH)',
  'GYPSUM',
  'HIGH PLASTICITY ORGANIC CLAY OR SILT (OH)',
  'LEAN CLAY (CL)',
  'LEAN TO FAT CLAY (CL-CH)',
  'LIMESTONE',
  'LOW PLASTICITY ORGANIC CLAY OR SILT (OL)',
  'PEAT',
  'POORLY GRADED GRAVEL (GP)',
  'POORLY GRADED GRAVEL WITH CLAY (GP-GC)',
  'POORLY GRADED GRAVEL WITH CLAY (GP-GM)',
  'POORLY GRADED SAND (SP)',
  'POORLY GRADED SAND WITH CLAY (SP-SC)',
  'POORLY GRADED SAND WITH SILT (SP-SM)',
  'SANDSTONE',
  'SANDSTONE/SHALE',
  'SANDY FAT CLAY (CH)',
  'SANDY LEAN CLAY (CL)',
  'SANDY SILT',
  'SHALE',
  'SILT',
  'SILTY CLAY (CL-ML)',
  'SILTY CLAYEY SAND (SC-CM)',
  'SILTY GRAVEL (GM)',
  'SILTY SAND (CM)',
  'SOIL AND WEATHERED ROCK',
  'TILL',
  'WEATHERED DOLOMITE',
  'WEATHERED LIMESTONE',
  'WEATHERED SANDSTONE',
  'WEATHERED SHALE',
  'WELL GRADED GRAVEL (GW)',
  'WELL GRADED GRAVEL WITH CLAY (GW-GC)',
  'WELL GRADED GRAVEL WITH SILT (GW-GM)',
  'WELL GRADED SAND (SW)',
  'WELL GRADED SAND WITH CLAY (SW-SC)',
  'WELL GRADED SAND WITH SILT (SW-SM)',
  'CLAYEY SHALE',
];

export var ConsistencyVal = [
  '---',
  'Very Loose',
  'Loose',
  'Medium Dense',
  'Dense',
  'Very Dense',
  'Very Soft',
  'Soft',
  'Medium Stiff',
  'Stiff',
  'Very Stiff',
  'Hard',
];

export var ColorVal = [
  '---',
  'black',
  'bluish black',
  'bluish gray',
  'brown',
  'brownish yellow',
  'dark bluish gray',
  'dark brown',
  'dark gray',
  'dark grayish brown',
  'dark grayish green',
  'dark greenish gray',
  'dark olive brown',
  'dark olive gray',
  'dark red',
  'dark reddish brown',
  'dark reddish gray',
  'dark yellowish brown',
  'dusky red',
  'gray',
  'grayish brown',
  'grayish black',
  'grayish gray',
  'light bluish gray',
  'light brown',
  'light brownish gray',
  'light gray',
  'light olive brown',
  'light olive gray',
  'light red',
  'light reddish brown',
  'light reddish gray',
  'light yellowish brown',
  'olive',
  'olive brown',
  'olive gray',
  'olive yellow',
  'pale brown',
  'pale green',
  'pale olive',
  'pale red',
  'pale yellow',
  'pink',
  'pinkish gray',
  'pinkish white',
  'red',
  'reddish black',
  'reddish brown',
  'reddish gray',
  'reddish yellow',
  'strong brown',
  'very dark brown',
  'very dark grayish brown',
  'very dark grey',
  'very dusky red',
  'very pale brown',
  'weak red',
  'white',
  'yellow',
  'yellowish brown',
  'yellowish red',
];

export var GrainSizeVal = [
  '---',
  'Coarse Grained',
  'Fine Grained',
  'Fine to Coarse Grained',
  'Fine to Medium Grained',
  'Medium Grained',
  'Medium to Coarse Grained',
];

export var PlasticityVal = [
  '---',
  'Medium Plasticity',
  'Low Plasticity',
  'High Plasticity',
];

export var MoistureVal = ['---', 'Dry', 'Moist', 'Wet', 'Saturated'];

export var RMRVal = [
  '---',
  'Very Poor Rock Mass Quality',
  'Poor Rock Mass Quality',
  'Fair Rock Mass Quality',
  'Good Rock Mass Quality',
  'Very Good Rock Mass Quality',
];

export var DepositionVal = [
  '---',
  'Fill',
  'Residual',
  'Alluvial',
  'Colluvial',
  'Loess',
  'Aeolian',
  'Fluvial',
  'Lacustrine',
  'Marine',
  'Weathered Rock',
  'Bedrock',
  'Glacial Till',
];

export var LineTypeVal = [
  '---',
  'None',
  'Solid',
  'Dash',
  'Dot',
  'Dash-Dot',
  'Dash-Dot-Dot',
  'Dash-Dash-Dot',
  'Dash 2',
  'Dot 2',
  'Dash-Dot 2',
  'Dash-Dash-Dot 2',
  'Dash 3',
  'Dot 3',
  'Dash-Dot 3',
  'Dash-Dot-Dot 3',
  'Dash-Dash-Dot 3',
];
